config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users
  resources :instructors

  resources :students do
    resources :attendances
  end

  resources :producers do
    resources :cohorts do
      get '/overview' => 'cohorts#overview'
    end
  end

  resources :cohorts do
    get '/overview' => 'cohorts#overview'
    get '/calendar' => 'cohorts#calendar'
    resources :students do
      resources :attendances
    end
  end

  resources :attendances

  # session links
  get  "/", to: "sessions#new"                 # sign in form
  post "/sessions", to: "sessions#create"      # log in
  delete "/sessions", to: "sessions#destroy"   # log out

  post "sms", to: "twilio#index"

end

app/models/cohort.rb
class Cohort < ActiveRecord::Base

  has_many   :instructors
  has_many   :students
  belongs_to :producer


  # This gets every student that is part of a specific cohort from the API and Creates them in our Database.
  def create_students
    students_url = "http://104.131.73.180/api/v1/cohorts/#{self.id}/students"
    students = HTTParty.get(students_url)
    students["students"].each do |student|
      new_student = Student.create(
        id: student["id"],
        name: student["data"]["first"] + " " + student["data"]["last"],
        email: student["contact"]["email"],
        cohort_id: self.id,
        phone_number: student["contact"]["phone"],
        password: "12345"
        )
      # Pony.mail(:to => new_student.email, :from => 'me@ga.co', :subject => 'New Account for GA Attendance created', :body => "Hello there, #{new_student.name}! We have created an account for you to track your attendance at GA. Your temporary password is 12345. Please log in soon to change it!")
    end
  end

  def create_instructors
    cohort_url = "http://104.131.73.180/api/v1/cohorts/#{self.id}"
    cohort = HTTParty.get(cohort_url)
    employee_url = "http://104.131.73.180/api/v1/employees"
    employees = HTTParty.get(employee_url)

    instructors_hash = {}

    instructors = cohort["cohorts"].first["instructor_ids"]

    employees["employees"].each do |employee|
      if employee["role"] == "instructor"
        key = employee["id"]
        instructors_hash[key] = employee
      end
    end

    cohort["cohorts"].first["instructor_ids"].each do |instructor_id|
      instructors_hash[instructor_id]["cohort"] = cohort["cohorts"].first["id"]
    end

    instructors_hash.each_pair do |id, instructor|
      if instructors.include? id
        new_instructor = Instructor.create(
          name:  instructor["data"]["first"] + " " + instructor["data"]["last"],
          email: instructor["contact"]["email"],
          cohort_id: instructor["cohort"],
          id: id,
          password: "12345"
        )
        # Pony.mail(:to => new_instructor.email, :from => 'me@ga.co', :subject => 'New Account for GA Attendance created', :body => "Hello there, #{new_instructor.name}! We have created an account for you to track your students' attendance at GA. Your temporary password is 12345. Please log in soon to change it!")
      end
    end
  end

  def create_array_of_attendance
    cohort_attendance = []
    self.students.each { |s| cohort_attendance << s.attendances }
    cohort_attendance.flatten!
  end

  def calculate_total_unexcused_absence
    cohort_attendance = create_array_of_attendance
    absences = cohort_attendance.select do |attendance|
      attendance.absence_type == "Unexcused"
    end
    absences.count
  end

  def calculate_total_excused_absence
    cohort_attendance = create_array_of_attendance
    absences = cohort_attendance.select do |attendance|
      attendance.absence_type == "Excused"
    end
    absences.count
  end

  def calculate_total_lates
    cohort_attendance = create_array_of_attendance
    lates = cohort_attendance.select do |attendance|
      attendance.absence_type == "Late"
    end
    lates.count
  end

  def attendance_today
    today = self.create_array_of_attendance.select do |a|
      a[:date] == Date.today
    end
  end

  def attendance_yesterday
    yesterday = self.create_array_of_attendance.select do |a|
      a[:date] == Date.today - 1
    end
  end

  def attendance_per_date(date)
    day = self.create_array_of_attendance.select do |a|
      a[:date] == date
    end
  end

  def unexcused(date)
    day = attendance_per_date(date)
    absences = day.select do |a|
      a[:absence_type] == "Unexcused"
    end
  end

  def excused(date)
    day = attendance_per_date(date)
    absences = day.select do |a|
      a[:absence_type] == "Excused"
    end
  end

  def late(date)
    day = attendance_per_date(date)
    lates = day.select do |a|
      a[:absence_type] == "Late"
    end
  end

  def today_unexcused
    today = attendance_today
    absences = today.select do |a|
      a[:absence_type] == "Unexcused"
    end
  end

  def today_excused
    today = attendance_today
    excused = today.select do |a|
      a[:absence_type] == "Excused"
    end
  end

  def today_late
    today = attendance_today
    late = today.select do |a|
      a[:absence_type] == "Late"
    end
  end

  def yesterday_unexcused
    yesterday = attendance_yesterday
    absences = yesterday.select do |a|
      a[:absence_type] == "Unexcused"
    end
  end

  def yesterday_excused
    yesterday = attendance_yesterday
    excused = yesterday.select do |a|
      a[:absence_type] == "Excused"
    end
  end

  def yesterday_late
    yesterday = attendance_yesterday
    late = yesterday.select do |a|
      a[:absence_type] == "Late"
    end
  end

end

app/controllers/cohorts_controller.rb
œ class CohortsController < ApplicationController

    before_action :authenticate, :authorize_instructor, :make_home_button

  def new
    url = "http://104.131.73.180/api/v1/cohorts"
    @cohorts = HTTParty.get(url)
    @cohort = Cohort.new
    
  end

  def create
    cohort = Cohort.new cohort_params
    if Cohort.exists?(cohort.id)
      redirect_to '/new'
    else
      cohort.save
      cohort.create_students
      cohort.create_instructors
      redirect_to @home
    end
  end

  def index
    @cohorts
    if params[:producer_id]
      @producer = Producer.find(params[:producer_id])
      @cohorts = @producer.cohorts
    end
  end

  def overview

    cohort = Cohort.find(params[:cohort_id])
    @unexcused_absence = cohort.calculate_total_unexcused_absence
    @excused_absence = cohort.calculate_total_excused_absence
    @lates = cohort.calculate_total_lates
    # gon.lates = @lates

    @cohort = Cohort.find(params[:cohort_id])
    @unexcused_absence = @cohort.calculate_total_unexcused_absence
    @excused_absence = @cohort.calculate_total_excused_absence
    @lates = @cohort.calculate_total_lates
  end

  # GET cohorts/:id
  def show
    @cohort = Cohort.find(params[:id])
    # if we're logged in as instructor the ID would be in session
    @user = User.find(session[:user_id])
    # @instructor = Instructor.find(2)
  end

  def calendar
    @date = params[:date].to_date
    @cohort = Cohort.find(params[:cohort_id])
    @excused = @cohort.excused(@date)
    @unexcused = @cohort.unexcused(@date)
    @late = @cohort.late(@date)
  end

  def cohort_params
    params.permit(
      :id,
      :name,
      :starts_on,
      :ends_on,
      :phone_number,
      :producer_id
    )
  end

end

app/views/cohorts/calendar.html.erb
<h1><%= @cohort.name %></h1>

<%= button_to "Home", @home , method: "get" %>


<%= link_to "Yesterday", cohort_calendar_path(@cohort, :date => Date.today - 1) %>
<%= link_to "Today", cohort_calendar_path(@cohort, :date => Date.today) %>
<h3>Attendance for <%= @date.strftime("%A, %b %d %Y") %></h3>
<table>
  <tr>
    <th>Name</th>
    <th>Late</th>
    <th>Excused</th>
    <th>Unexcused</th>
  </tr>
    <% @late.each do |late| %>
  <tr>
    <td><%= link_to late.student.name, student_path(late.student) %></td>
    <td>x</td>
    <td> </td>
    <td> </td>
    <td><%= button_to "Edit", edit_student_attendance_path(late.student, late), method: "get" %></td>
    <td><%= button_to "Delete", attendance_path(late), method: "delete" %></td>
  </tr>
    <% end %>
    <% @excused.each do |excused| %>
  <tr>
    <td><%= link_to excused.student.name, student_path(excused.student) %></td>
    <td> </td>
    <td>x</td>
    <td> </td>
    <td><%= button_to "Edit", edit_student_attendance_path(excused.student, excused), method: "get" %></td>
    <td><%= button_to "Delete", attendance_path(excused), method: "delete" %></td>
  </tr>
    <% end %>
    <% @unexcused.each do |unexcused| %>
  <tr>
    <td><%= link_to unexcused.student.name, student_path(unexcused.student) %></td>
    <td> </td>
    <td> </td>
    <td>x</td>
    <td><%= button_to "Edit", edit_student_attendance_path(unexcused.student, unexcused), method: "get" %></td>
    <td><%= button_to "Delete", attendance_path(unexcused), method: "delete" %></td>
  </tr>
    <% end %>
</table>

app/views/cohorts/index.html.erb
<div class = "logout">
  <%= button_to "Add new Cohorts", '/cohorts/new', method: "get" %>
</div>


<h1>Hello, <%= @producer.name %>!</h1>

<h2>Here are your Cohorts: </h2>
<ul>
<% @cohorts.each do |cohort| %>
  <li>
    <h4 class="cohort-name"><%= link_to cohort.name, producer_cohort_overview_path(@producer, cohort) %></h4>
  </li>
<!-- "/overview/#{@cohorts}" -->
<% end %>
</ul>

app/views/cohorts/new.html.erb
<h1>Add a Cohort:</h1>

<div="cohort-add-buttons">
<% @cohorts["cohorts"].each do |cohort| %>
  <h3><%= link_to cohort["name"], new_cohort_student_path(cohort["id"]) %></h3>

  <div class="add-cohort-button">
    <%= button_to "Add", "/cohorts", params: {
        id: cohort["id"],
        name: cohort["name"],
        starts_on: cohort["dates"]["starts_on"],
        ends_on: cohort["dates"]["ends_on"],
        producer_id: cohort["producer_id"]
      },
    method: "post" %>
  </div>
<% end %>
</div>

app/views/cohorts/overview.html.erb
<%= button_to "Students", cohort_students_path(@cohort), method: "get" %>

<!-- Unexcused: <%= @unexcused_absence %>
Excused: <%= @excused_absence %>
Lates <%= @lates %> -->



<canvas id="myChart" width="900" height="300"></canvas>
<!-- legend template -->
<div class="row">
    <div class="four columns" style="color: rgba(219,20,20,0.7)">Late <%= @lates %> </div>
    <div class="four columns" style="color: rgba(28,237,9,0.9)">Excused Absence <%= @excused_absence %></div>
    <div class="four columns" style="color:rgba(49,88,230,.9)">Unexcused Absence <%= @unexcused_absence %></div>
</div>


<script type="text/javascript">
  var data = {
    labels: ["<%= @cohort.name %>"],
    datasets: [
        {
            label: "Lateness",
            fillColor: "rgba(219,20,20,0.7)",
            strokeColor: "rgba(220,220,220,0.8)",
            highlightFill: "rgba(220,220,220,0.75)",
            highlightStroke: "rgba(220,220,220,1)",
            data: [<%= @lates %>]
        },
        {
            label: "Excused Absence",
            fillColor: "rgba(28,237,9,0.9)",
            strokeColor: "rgba(151,187,205,0.8)",
            highlightFill: "rgba(151,187,205,0.75)",
            highlightStroke: "rgba(151,187,205,1)",
            data: [<%= @excused_absence %>]
        },
        {
            label: "Unexcused Absence",
            fillColor: "rgba(49,88,230,.9)",
            strokeColor: "rgba(220,220,220,0.8)",
            highlightFill: "rgba(220,220,220,0.75)",
            highlightStroke: "rgba(220,220,220,1)",
            data: [<%= @unexcused_absence %>]
        }

    ]
    };
</script>

app/views/cohorts/show.html.erb
<div class = "logout">
  <%= button_to "Attendance Chart", cohort_overview_path(@cohort), method: "get" %>
  <%= link_to "Calendar View", cohort_calendar_path(@cohort, :date => Date.today) %>
</div>


<h1><%= @cohort.name %></h1>



Instructors: <br />
<% @cohort.instructors.each do |instructor| %>
  <%= instructor.name %><br />
<% end %>


<br /> <br />
<% c1_attendance = [] %>
<% Cohort.first.students.each do |s| %>
  <% c1_attendance << s.attendances  %>
<% end %>


Total Cohort Absences to Date:<%= c1_attendance.flatten.count %>


Total Class Absences:   <%= c1_attendance.flatten.count %>



<ul class="unordered-list-of-students">
  <% total= @cohort.students.each do |student| %>
   <li>
      <%= student.name %> - Late: <%= student.count_lateness %>, Unexcused: <%= student.count_unexcused %>, Excused: <%= student.count_excused %>, Total Absences: <%=student.total_absences %><br />

      <div class="absences">

      <%= form_for([@cohort, student, student.attendances.new]) do |f| %>
        <%= f.submit "Late" %>
      <% end %>
      </div>

      <div class="absences">
      <%= form_for([@cohort, student, student.attendances.new]) do |f| %>
        <%= f.submit "Unexcused" %>
      <% end %>
      </div>

      <div class="absences">
      <%= form_for([@cohort, student, student.attendances.new]) do |f| %>
        <%= f.submit "Excused" %>
      <% end %>
      </div>

      <br /><br />
   </li>
  <% end %>
</ul>