config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users
  resources :instructors

  resources :students do
    resources :attendances
  end

  resources :producers do
    resources :cohorts do
      get '/overview' => 'cohorts#overview'
    end
  end

  resources :cohorts do
    get '/overview' => 'cohorts#overview'
    get '/calendar' => 'cohorts#calendar'
    resources :students do
      resources :attendances
    end
  end

  resources :attendances

  # session links
  get  "/", to: "sessions#new"                 # sign in form
  post "/sessions", to: "sessions#create"      # log in
  delete "/sessions", to: "sessions#destroy"   # log out

  post "sms", to: "twilio#index"

end

app/models/student.rb
class Student < User

  belongs_to :cohort
  has_many   :attendances
  has_many   :instructors, through: :cohort
  has_one    :producer, through: :cohort

  has_secure_password

  attr_accessor :flash_notice

  def self.create_student_records_for_cohort(cohort_id)
  	students_url = "http://104.131.73.180/api/v1/cohorts/#{cohort_id}/students"
		students = HTTParty.get(students_url)
		# binding.pry
		@students = students["students"].map do |student|
			 student = Student.new(name:  student["data"]["first"] + " " + student["data"]["last"],
			 	email: student["contact"]["email"],
			 	password: "abcd")
			 student.save
		end
  end



  def late_on?(date)
    attendances.where(date: date, absence_type: "Late").any?

  end

  def unexcused_on?(date)
    attendances.where(date: date, absence_type: "Unexcused").any?
  end

  def excused_on?(date)
    attendances.where(date: date, absence_type: "Excused").any?
  end

  def late?
    late_on?(Date.today)
  end

  def count_lateness
    self.attendances.where(absence_type: "Late").length
  end

  def count_unexcused
    self.attendances.where(absence_type: "Unexcused").length
  end

  def count_excused
    self.attendances.where(absence_type: "Excused").length
  end

  def total_absences
    self.attendances.count
  end

  def total_class_absences
    self.all.attendances.count
  end

    def late_more_than_four_times?
    lateness = self.attendances.select do |attendance|
      attendance.absence_type == "Late"
    end
    lateness.count >= 3
  end

  def delete_latenesses
    lateness = self.attendances.select do |attendance|
      attendance.absence_type == "Late"
    end
    lateness.each do |late|
      Attendance.delete(late.id)
    end
  end

  def converting_four_lates_into_one_absence
    delete_latenesses
    attendance = Attendance.new(
      absence_type: "Unexcused",
      student_id: self.id,
      date: Date.today
    )
  end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	before_action :authenticate, :authorize_student, :make_home_button

	def new
		@cohort_id = params[:cohort_id]
		students_url = "http://104.131.73.180/api/v1/cohorts/#{@cohort_id}/students"
		@students = HTTParty.get(students_url)
		@data = {name: 'phil', absent: true}.to_json
	end

	def create
		student = Student.new student_params
		student.save
		redirect_to '/index'
	end

	def show
		@student = Student.find(params[:id])
		@lateness = @student.count_lateness
		@unexcused = @student.count_unexcused
		@excused = @student.count_excused
		if (current_user != @student) && (current_user.type == "Student")
			redirect_to student_path(current_user)
		end
	end

	def index
		@students = Cohort.find(params[:cohort_id]).students
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		student = Student.find(params[:id])
	end

	def student_params
		params.permit(
			:name,
			:email,
			:cohort_id,
			:password
		)
	end
end

app/views/students/edit.html.erb
<h1>Edit this student's information:</h1>

<%= form_for @student do |f| %>
  <%= f.label :name, "Name" %>:
  <%= f.text_field :name %><br>
  <%= f.label :email, "Email" %>:
  <%= f.text_field :email %><br>
  <%= f.label :phone_number, "Phone Number" %>:
  <%= f.text_field :phone_number %><br>
  <%= f.label :cohort_id, "Cohort" %>:
  <%= f.text_field :cohort_id %><br>
  <%= f.label :password, "Password" %>:
  <%= f.text_field :password %><br>
<% end %>

app/views/students/index.html.erb
<h1>Here are the students:</h1>
	<ul>
		<% @students.each do |student| %>
		<li>
      <%= link_to student.name, student_path(student) %>
      <%= link_to "Edit student", edit_student_path(student) %>
    </li>
		<% end %>
	</ul>

app/views/students/new.html.erb
<h1>Add a new Student to <%= Cohort.find(@cohort_id).name %>:</h1>

<% @students["students"].each do |student| %>

  <h3><%= student["data"]["first"] + " " + student["data"]["last"] %></h3>

  <%= button_to "Add", "/students", params: {
      name: student["data"]["first"] + " " + student["data"]["last"],
      email: student["contact"]["email"],
      cohort_id: @cohort_id,
      password: "12345"
    } %>

  <% end %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<!-- Lateness: <%= @lateness %><br>
Unexcused Absence: <%= @unexcused %><br>
Excused Absence: <%= @excused %> -->

<!-- legend template -->
<canvas id="myChart" width="900" height="300"></canvas>
<!-- legend template -->
<div class="row">
    <div class="four columns" style="color: rgba(219,20,20,0.7)">Late <%= @lates %> </div>
    <div class="four columns" style="color: rgba(28,237,9,0.9)">Excused Absence <%= @excused_absence %></div>
    <div class="four columns" style="color:rgba(49,88,230,.9)">Unexcused Absence <%= @unexcused_absence %></div>
</div>




<script type="text/javascript">
  var data = {
    labels: ["<%= @student.name %>"],
    datasets: [
        {
            label: "Lateness",
            fillColor: "rgba(219,20,20,0.7)",
            strokeColor: "rgba(220,220,220,0.8)",
            highlightFill: "rgba(220,220,220,0.75)",
            highlightStroke: "rgba(220,220,220,1)",
            data: [<%= @lateness %>]
        },
        {
            label: "Excused Absence",
            fillColor: "rgba(28,237,9,0.9)",
            strokeColor: "rgba(151,187,205,0.8)",
            highlightFill: "rgba(151,187,205,0.75)",
            highlightStroke: "rgba(151,187,205,1)",
            data: [<%= @excused %>]
        },
        {
            label: "Unexcused Absence",
            fillColor: "rgba(49,88,230,.9)",
            strokeColor: "rgba(220,220,220,0.8)",
            highlightFill: "rgba(220,220,220,0.75)",
            highlightStroke: "rgba(220,220,220,1)",
            data: [<%= @unexcused %>]
        }

    ]
};

  if(<%= @unexcused %> >= 4) {
    window.onload = function(){
        swal("You have missed class 4 or more times!", "Please speak to an instructor.", "warning");
    }
  }

</script>



<!--


<h1><%= @student.name %>, Yo </h1>
<%= @lateness %>
<%= @unexcused %>
<%= @excused %>





<script type="text/javascript">
  var data = {
    labels: ["<%= @student.name %>"],
    datasets: [
        {
            label: "Lateness",
            fillColor: "rgba(220,220,220,0.5)",
            strokeColor: "rgba(220,220,220,0.8)",
            highlightFill: "rgba(220,220,220,0.75)",
            highlightStroke: "rgba(220,220,220,1)",
            data: [<%= @lateness %>]
        },
        {
            label: "Excused Absence",
            fillColor: "rgba(151,187,205,0.5)",
            strokeColor: "rgba(151,187,205,0.8)",
            highlightFill: "rgba(151,187,205,0.75)",
            highlightStroke: "rgba(151,187,205,1)",
            data: [<%= @excused %>]
        },
        {
            label: "Unexcused Absence",
            fillColor: "rgba(120,120,120,.9)",
            strokeColor: "rgba(220,220,220,0.8)",
            highlightFill: "rgba(220,220,220,0.75)",
            highlightStroke: "rgba(220,220,220,1)",
            data: [<%= @unexcused %>]
        }

    ]
};

  if(<%= @unexcused %> >= 4) {
    alert('Please speak to your instructor about missing class.');
  }

</script>
 -->