config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users
  resources :instructors

  resources :students do
    resources :attendances
  end

  resources :producers do
    resources :cohorts do
      get '/overview' => 'cohorts#overview'
    end
  end

  resources :cohorts do
    get '/overview' => 'cohorts#overview'
    get '/calendar' => 'cohorts#calendar'
    resources :students do
      resources :attendances
    end
  end

  resources :attendances

  # session links
  get  "/", to: "sessions#new"                 # sign in form
  post "/sessions", to: "sessions#create"      # log in
  delete "/sessions", to: "sessions#destroy"   # log out

  post "sms", to: "twilio#index"

end

app/models/producer.rb
class Producer < User
  has_many   :cohorts
  has_many   :instructors, through: :cohort
  has_many   :students, through: :cohort

  # has_many   :students, through: :cohort
  # has_secure_password

  # def self.create_producer_records()
  # 	employee_url = "http://104.131.73.180/api/v1/employees"
  #   employees = HTTParty.get(employee_url)
  #   @instructors = employees["employees"].select do |employee|
  #   	employee["role"] == "producer"
  #       instructor = Instructor.new(name: employees["data"]["first"] + " " + employees["data"]["last"] ,
  #       	email: employees["contact"]["email"], cohort_id: cohort_id[""])
  #       instructor.save
  #     end
  # end
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController

  before_action :authenticate, :authorize_producer, :make_home_button

  def new
    employee_url = "http://104.131.73.180/api/v1/employees"
    employees = HTTParty.get(employee_url)
    @producers = employees["employees"].select do |employee|
      employee["role"] == "producer"
    end
    cohort_url = "http://104.131.73.180/api/v1/cohorts"
    @cohorts = HTTParty.get(cohort_url)
    @producer = Producer.new
  end

  def create
    producer = Producer.new producer_params
    producer.save
    redirect_to '/producers'
  end

  def index
    @cohorts = Cohort.all
    # cohorts_url = "http://104.131.73.180/api/v1/cohorts"
    # cohorts = HTTParty.get(cohorts_url)
    # employee_url = "http://104.131.73.180/api/v1/employees"
    # employees = HTTParty.get(employee_url)
    # # user = User.find(session[:user_id])
    # # binding.pry
    # user = User.find(11)
    # @producer = employees["employees"].select do |employee|
    #   employee["contact"]["email"] == user.email
    # end
    # # binding.pry
    # producer_id = @producer.first["id"]
    # @cohorts = cohorts["cohorts"].select do |cohort|
    #   cohort["producer_id"] == producer_id
    # end
  end

  def show
    # cohorts_url = "http://104.131.73.180/api/v1/cohorts/#{params[:id]}/students"
    # students = HTTParty.get(cohorts_url)
    # emails = students["students"].map do |student|
    #   student["contact"]["email"]
    # end
    # binding.pry
    # @cohort_students
  end

  def producer_params
    params.permit(
      :id,
      :name,
      :email,
      :password
    )
  end

end

app/views/producers/all_producers.html.erb
all_producers.html.erb

app/views/producers/index.html.erb
<h1>Hello <%#= @producer.first["data"]["first"] %>! </h1>
<h2>Here are your cohorts:</h2>

<%# @cohorts.each do |cohort| %>
  <h3><%#= link_to cohort["name"], producer_path(cohort["id"]) %></h3>
<%# end %>

<% @cohorts.each do |cohort| %>

  <h3><%= cohort.name %></h3>

<% end %>

app/views/producers/new.html.erb
<h1>Add a new Producer:</h1>

<% @producers.each do |producer| %>
  <h3><%= producer["data"]["first"] + " " + producer["data"]["last"] %></h3>

  <% this_cohort = @cohorts["cohorts"].select do |cohort| %>
    <% cohort["producer_id"] == producer["id"] %>
  <% end %>

  <%= button_to "Add", "/producers", params: {
      id: producer["id"],
      name: producer["data"]["first"] + " " + producer["data"]["last"],
      email: producer["contact"]["email"],
      password: "12345"
    },
    method: "post" %>
<% end %>

app/views/producers/show.html.erb
show.html.erb